on:
  pull_request:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Auto-approve dependabot PRs for minor or test-only dependency upgrades
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: ^1.20.3
    - uses: goto-bus-stop/setup-zig@v2
    - run: ./release.sh
    - uses: actions/upload-artifact@v3
      with:
        name: release
        path: release/*
    - name: Dependabot metadata
      if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
      id: dependabot-metadata
      uses: dependabot/fetch-metadata@v1.3.1
    - name: Enable auto-merge for Dependabot PRs
      if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
      run: gh pr merge --auto --rebase "$PR_URL"
      env:
        GITHUB_TOKEN: ${{ secrets.DEPENDABOT_PUSH_TOKEN }}
        PR_URL: ${{github.event.pull_request.html_url}}
    - name: Approve patch and minor updates for Dependabot PRs
      if: ${{ (github.event.pull_request.user.login == 'dependabot[bot]') &&
          ((steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch') || (steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor')) }}
      run: |
        gh api --method POST -H 'Accept: application/vnd.github+json' '/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/reviews' -f event='APPROVE'
      env:
        GH_TOKEN: ${{ secrets.DEPENDABOT_PUSH_TOKEN }}
        PR_NUMBER: ${{github.event.pull_request.number}}
    - name: Approve major updates of development dependencies for Dependabot PRs
      if: ${{ (github.event.pull_request.user.login == 'dependabot[bot]') &&
          (steps.dependabot-metadata.outputs.update-type == 'version-update:semver-major') && (steps.dependabot-metadata.outputs.dependency-type == 'direct:development') }}
      run: |
        gh api --method POST -H 'Accept: application/vnd.github+json' '/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/reviews' -f event='APPROVE'
      env:
        GH_TOKEN: ${{ secrets.DEPENDABOT_PUSH_TOKEN }}
        PR_NUMBER: ${{github.event.pull_request.number}}

