name: Prerelease

on:
  push:
    branches:
      - main

jobs:

  Prerelease:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20.2

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build
        run: |
          mkdir release
          cd sqlite
          go generate
          mv s3db.so ../release/s3db-prerelease-linux-amd64.sqlite-ext.so
          cd ../release
          gzip -9 s3db-prerelease-linux-amd64.sqlite-ext.so

      - name: Create Release
        id: create_release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          files: |
            release/s3db-prerelease-linux-amd64.sqlite-ext.so.gz

